### PR TITLE
Added configs for NTU-v1.

### PR DESCRIPTION
**Pull request by Gateway2745**
Added configs for NTU-v1.

### CODE REVIEW

**Review by FarzanehAskari — COMMENTED** [review]
Looks pretty good. 

for consistency we add v1 or v2 to the experiments names for NTU. Similar to UT dataset where we add s1 and s2 for set1 and set2 respectively. See final_runs.sh for UT examples. Applying this change will change the weights_filepaths address for the fusion models. 

Make sure the NTU weights_filepaths are saved under models/NTU (ad not NTU-V1, etc).

**Comment by Gateway2745** [comment]
Oh alright. So instead of having the config path as `configs/NTU-V1/`, I should instead make it `configs/NTU/v1/`, but have the weights still saved to `models/NTU/`?

**Comment by FarzanehAskari** [comment]
sorry I didn't make myself clear.

Oh alright. So instead of having the config path as `configs/NTU-V1/`, I should instead make it `configs/NTU/v1/` : yes

but have the weights still saved to `models/NTU/`?: no, what I meant is to make sure the weight_filepaths you pass to the config file for fusion models is correct.

**Comment by Gateway2745** [comment]
Okay got it :+1:. So the models will be saved to `models/NTU/v1` and I will change the weight_filepaths accordingly for the fusion models.

**Comment by FarzanehAskari** [comment]
+ changing the experiments names to reflect the NTU version

**Pull request merged**
